Decrypt now checks if file changed for decrypting, git hooks bugfix

diff --git a/dotgit b/dotgit
--- a/dotgit
+++ b/dotgit
@@ -153,13 +153,13 @@ function safeguards
 		exit 1
 	fi
 
-	if [ ! -d "$REPO/.git" ]; then
-		echo "This does not seem to be a git repository. Aborting..."
+	if [ ! -f "$REPO/cryptlist" ]; then
+		echo "Cryptlist not found. Aborting..."
 		exit 1
 	fi
 
-	if ! grep -q -v "#" "$REPO/filelist"; then
-		echo "Filelist empty. Aborting..."
+	if [ ! -d "$REPO/.git" ]; then
+		echo "This does not seem to be a git repository. Aborting..."
 		exit 1
 	fi
 
@@ -314,7 +314,8 @@ function encrypt
 	for i in $(find -not -type d -and -not -type l); do
 		mkdir -p $(dirname "$DOTFILES/$i")
 		if [ -f "$DOTFILES/$i" ]; then
-			if [ "$(sha1sum "$i")" == "$(cat "$DOTFILES/$i.hash")" ]; then
+			sum=$(sha1sum "$i" | sed 's/\ .*//')
+			if [ "$sum" == "$(cat "$DOTFILES/$i.hash")" ]; then
 				continue;
 			fi
 			rm "$DOTFILES/$i"
@@ -323,60 +324,20 @@ function encrypt
 		echo "-->Encrypting $(echo $i | cut -c 3-)"
 		gpg -c --batch --passphrase-file "$REPO/tmp" -o "$DOTFILES/$i" "$i"
 		chmod $(stat -c '%a' "$i") "$DOTFILES/$i"
-		sha1sum "$i" > "$DOTFILES/$i.hash"
+		sha1sum "$i" | sed 's/\ .*//' > "$DOTFILES/$i.hash"
 	done
 }
 
 function decrypt
 {
-	cd "$DOTFILES"
-	if [ -z "$PASSWD" ]; then pprompt "decryption"; fi
+	for i in $CRYPTFILES; do
+		if [[ ! $i =~ *:* ]]; then i=$(echo "$i:common"); fi
 
-	for i in $(echo $CRYPTFILES | grep -v ":"); do
-		if [ "$(dirname "$i")" != "." ]; then
-			mkdir -p "$(dirname "$DMZ/$i")"
-		fi
-
-		if [ ! -f "$DOTFILES/common/$i"  ]; then
-			echo "--> File $i does not yet exist in the repo. Please run"\
-				"update/encrypt to populate repository"
-			continue
-		fi
-
-		echo "-->Decrypting $i"
-		if [ -h "$i" ]; then
-			if [ -f "$DMZ/common/$i" ]; then
-				rm "$DMZ/common/$i"
-				cp -P --parents "$i" "$DMZ"
-			fi
-		else
-			gpg --quiet --batch --decrypt --passphrase-file "$REPO/tmp" \
-				--output "$REPO/mid" "$DOTFILES/common/$i"
-			chmod $(stat -c '%a' "$DOTFILES/common/$i") "$REPO/mid"
-			if [ -f "$DMZ/common/$i" ]; then
-				if ! diff "$DMZ/common/$i" "$REPO/mid" > /dev/null; then
-					echo -e "Your local version of $i differs from the version"\
-						"decrypted from the repository\n";
-
-					if ! yesno "Do you want to overwrite the local version?"\
-						"[Y/n]: "; then
-						rm "$DMZ/common/$i"
-						cp "$REPO/mid" "$DMZ/common/$i"
-					fi
-				fi
-			else
-				cp "$REPO/mid" "$DMZ/common/$i"
-			fi
-			rm "$REPO/mid"
-		fi
-	done
-
-	for i in $(echo $CRYPTFILES | grep ":"); do
 		ownrs=($(echo $i | rev | sed s/\:.*// | sed s/\,/\ /g | rev))
 		ownrs=($(for z in ${ownrs[@]}; do echo $z; done | sort))
 		filename=$(echo $i | sed s/\:.*//);
 
-		if [ ! -f "${ownrs[$k]}/$filename"  ]; then
+		if [ ! -f "$DOTFILES/${ownrs[$k]}/$filename"  ]; then
 			echo "--> File ${ownrs[$k]}/$filename does not yet exist in the"\
 				"repo.Please run update/encrypt to populate repository"
 			continue
@@ -386,16 +347,51 @@ function decrypt
 
 			mkdir -p "$(dirname "$DMZ/${ownrs[$k]}/$filename")"
 
+			copy=0
 			if [ -f "$DMZ/${ownrs[$k]}/$filename" ]; then
-				rm "$DMZ/${ownrs[$k]}/$filename"
+				if [ -h "$DMZ/${ownrs[$k]}/$filename" ]; then
+					copy=1
+				else
+					sum=$(sha1sum "$DMZ/${ownrs[$k]}/$filename" | \
+						sed 's/\ .*//')
+					temp="$DOTFILES/${ownrs[$k]}/$filename"
+					if [ -h "$temp" ]; then
+						temp=$(readlink "$temp")
+					fi
+
+					if [ "$sum" != "$(cat "$temp.hash")" ]; then
+						echo -e "Your local version of $filename differs from"\
+						"the version from the repository\n"
+
+						yesno "Do you want to overwrite the local version?"\
+						" [Y/n]: "
+
+						if [ $? == 1 ]; then copy=1; fi
+					fi
+				fi
+			else
+				copy=1
 			fi
 
-			if [ -h "${ownrs[$k]}/$filename" ]; then
-				cp -P --parents "${ownrs[$k]}/$filename" "$DMZ"
-			else
+			if [ $copy == 1 ]; then
+				if [ -f "$DMZ/${ownrs[$k]}/$filename" ]; then
+					rm "$DMZ/${ownrs[$k]}/$filename"
+				fi
+
+				if [ -h "$DOTFILES/${ownrs[$k]}/$filename" ]; then
+					cd "$DOTFILES"
+					cp -P --parents "${ownrs[$k]}/$filename" "$DMZ"
+					continue
+				fi
+
+				if [ -z "$PASSWD" ]; then pprompt "decryption"; fi
+
 				echo "-->Decrypting $filename"
-				gpg --batch --quiet --passphrase-file "$REPO/tmp" -o \
-					"$DMZ/${ownrs[$k]}/$filename" "${ownrs[$k]}/$filename"
+				gpg --quiet --batch --decrypt --passphrase-file "$REPO/tmp" \
+					--output "$REPO/mid" "$DOTFILES/${ownrs[$k]}/$filename"
+				chmod $(stat -c '%a' "$DOTFILES/${ownrs[$k]}/$filename") \
+					"$REPO/mid"
+				mv "$REPO/mid" "$DMZ/${ownrs[$k]}/$filename"
 			fi
 		done
 	done
@@ -851,13 +847,13 @@ function init
 	touch filelist
 	touch cryptlist
 	echo "dmz" >> .gitignore
-	echo "passwd" >> .gitignore
 	echo "tmp" >> .gitignore
+	echo "mid" >> .gitignore
 
 	echo "Creating encryption hooks..."
 	create=0
-	if [ -f "$REPO/.git/hooks/pre-commit" ]; then
-		if ! grep "dotgit encrypt" "$REPO/.git/hooks/pre-commit"; then
+	if [ -f "$REPO/.git/hooks/post-merge" ]; then
+		if ! grep "dotgit decrypt" "$REPO/.git/hooks/post-merge"; then
 			create=1
 		fi
 	else
@@ -865,8 +861,7 @@ function init
 	fi
 
 	if [ $create -eq 1 ]; then
-		# echo "dotgit encrypt" >> .git/hooks/pre-commit
-		# chmod +x .git/hooks/pre-commit
+		echo "exec < /dev/tty" >> .git/hooks/post-merge
 		echo "dotgit decrypt" >> .git/hooks/post-merge
 		chmod +x .git/hooks/post-merge
 	fi
@@ -891,7 +886,13 @@ function pdiff
 		sed 's/C/Copied/g')
 
 	echo -e "\nPlease note that this will not show changes to encrypted files"\
-	"until you run 'dotgit encrypt'\n\n$message"
+	"until you run 'dotgit encrypt'\n"
+
+	if [ -z "$message" ]; then
+		echo "No changes to repo..."
+	else
+		echo "$message"
+	fi
 
 	git reset -q
 }
